ANCHOR_RATIOS = [0.5, 1, 2]
ANCHOR_SIZES = [32, 64, 128, 256, 512]
ANCHORS_PER_PIXEL = len(ANCHOR_RATIOS)
DATASET_DIR = 'D:\Mask_RCNN\COCO'
DATASET_TYPE = 'val2017'
DEBUG = False

# this should be consistent with defined FPN network
FEATURE_STRIDES = [2**p for p in range(2, 7)]

IMG_SIZE_TRAIN = 1024
RPN_ANCHORS_TRAIN_PER_IMAGE = 256
RPN_TOP_K_FOR_TRAINING = 10000
RPN_TOP_K_FOR_INFERENCE = 10000

RPN_PROPOSEL_NUM = 1000
TRAIN_ROIS_PER_IMAGE = 128
ROIS_POS2NEG_RATIO = 1. / 3.
USE_GT_BBOX_IN_MASK_RCNN = False
MASK_OUTPUT_SHAPE = 28
BACKPROP_ROI = False
CLS_BBOX_ROI_POOL_SIZE = 7
MASK_ROI_POOL_SIZE = 14
ROI_MAX_IN_POOL_SIZE = 2
NUM_CLASSES = 81
MAX_GT_TRAIN_INSTANCES = 100
